#!/bin/bash
# first-light.sh: the whole "signing day" sequence for the Mac-attached Blackhole, in order,
# stopping at the first failure, with every step's output captured and appended to the journey
# log as a dated entry.
#
#   scripts/first-light.sh --team TEAMID --bhpy ~/code/blackhole-py --python .venv/bin/python
#   scripts/first-light.sh --sim --bhpy ~/code/blackhole-py --python .venv/bin/python   # rehearsal
#
# Steps (each gated on the previous):
#    1 environment          macOS / Xcode components / official tt / tt-station
#    2 card on the bus      tt-station local finds the P100A in the IORegistry
#    3 install + activate   install-dev.sh --team (dev-signed dext, SIP on); waits for your approval
#    4 driver attached      the card's IORegistry child is ttstation-blackhole
#    5 probe                read-only: IDs, BAR sizes, TLB/iATU registers                 (M1)
#    6 NOC read             probe --noc: ARC boot status + live telemetry                  (M2)
#    7 DMA loopback         probe --dma: chip↔host through the dext's PrepareDMA + iATU     (M3)
#    8 tt-station local     driver + live telemetry + right-sized models                    (M4)
#    9 broker + doctor      TTStationDriver serve; blackhole-py prerequisites all green
#   10 kernels compile      blackhole-py plans + compiles a matmul (host only)
#   11 matmul on the card   blackhole-py runs + fully validates it on the P100A
#
# --sim is the rehearsal you can run today: steps 3-8 are skipped (they need the dext), the broker
# is the simulated one, and step 11 becomes "boot() reaches the point where the chip must run code".
# It logs to a scratch file, not the journey, unless --log says otherwise.
#
# macOS ships bash 3.2: no associative arrays, no mapfile, no ${var,,}.
set -u

HERE="$(cd "$(dirname "$0")/.." && pwd)"            # macos/TTStationDriver
REPO="$(cd "$HERE/../.." && pwd)"
TEAM="" BHPY="" PY="python3" SIM=0 SKIP_INSTALL=0 LOG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --team) TEAM="${2:?}"; shift 2 ;;
    --bhpy) BHPY="${2:?}"; shift 2 ;;
    --python) PY="${2:?}"; shift 2 ;;
    --sim) SIM=1; shift ;;
    --skip-install) SKIP_INSTALL=1; shift ;;
    --log) LOG="${2:?}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$BHPY" ] || { echo "--bhpy <blackhole-py checkout> is required" >&2; exit 2; }
BHPY="$(cd "$BHPY" && pwd)" || exit 2
if [ $SIM -eq 0 ] && [ -z "$TEAM" ] && [ $SKIP_INSTALL -eq 0 ]; then
  echo "--team TEAMID is required (or --sim to rehearse, or --skip-install if already installed)" >&2; exit 2
fi
[ -n "$LOG" ] || if [ $SIM -eq 1 ]; then LOG="${TMPDIR:-/tmp}/first-light-sim.md"; else LOG="$REPO/docs/journey/egpu-p100-on-a-mac.md"; fi

HOSTAPP="/Applications/TTStationDriver.app/Contents/MacOS/TTStationDriver"
TTSTATION="$(command -v tt-station || echo "$REPO/target/release/tt-station")"
export PYTHONPATH="$HERE/bhpy${PYTHONPATH:+:$PYTHONPATH}"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/first-light.XXXXXX")"
BROKER_PID=""
if [ $SIM -eq 1 ]; then export TTBH_BROKER_SOCKET="$WORK/ttbh.sock"; fi   # short: AF_UNIX caps at 104 bytes

cleanup() {
  if [ -n "$BROKER_PID" ]; then kill "$BROKER_PID" 2>/dev/null; wait "$BROKER_PID" 2>/dev/null; fi
  rm -rf "$WORK"
}
trap cleanup EXIT

# ── logging ──────────────────────────────────────────────────────────────────────────────
STEP=0 RESULTS=""
MODE_LABEL="first light"; [ $SIM -eq 1 ] && MODE_LABEL="first-light rehearsal (--sim)"
{
  echo
  echo "---"
  echo
  echo "## $(date +%F): $MODE_LABEL"
  echo
  echo "*Generated by \`macos/TTStationDriver/scripts/first-light.sh\` at $(date '+%H:%M %Z') on $(scutil --get ComputerName 2>/dev/null || hostname).*"
  echo
} >> "$LOG"

# record NAME STATUS SECONDS OUTPUT_FILE
record() {
  local name="$1" status="$2" secs="$3" out="$4"
  RESULTS="$RESULTS$STEP|$name|$status|${secs}s
"
  {
    echo "### $STEP. $name: $status (${secs}s)"
    echo
    if [ -n "$out" ] && [ -s "$out" ]; then
      echo '```'
      # Readable and portable: last 40 lines, no ANSI colour codes, $HOME shown as ~.
      tail -40 "$out" | sed -e $'s/\x1b\\[[0-9;]*m//g' -e "s#$HOME#~#g"
      echo '```'
      echo
    fi
  } >> "$LOG"
}

# step NAME CMD...: run, show live, capture, record; stop the whole run on failure.
step() {
  STEP=$((STEP + 1))
  local name="$1"; shift
  local out="$WORK/step$STEP.txt" t0 rc
  printf '╔══ %s. %s\n' "$STEP" "$name"
  t0=$(date +%s)
  "$@" > "$out" 2>&1; rc=$?
  sed 's/^/║  /' "$out" | tail -40
  local secs=$(( $(date +%s) - t0 ))
  if [ $rc -eq 0 ]; then
    printf '╚══ PASS (%ss)\n\n' "$secs"; record "$name" PASS "$secs" "$out"
  else
    printf '╚══ FAIL: exit %s (%ss)\n\n' "$rc" "$secs"; record "$name" "FAIL (exit $rc)" "$secs" "$out"
    finish 1
  fi
}

# note NAME CMD...: like step, but never stops the run (used where --sim doesn't need the thing).
note() {
  STEP=$((STEP + 1))
  local name="$1"; shift
  local out="$WORK/step$STEP.txt" rc
  printf '╔══ %s. %s (informational)\n' "$STEP" "$name"
  "$@" > "$out" 2>&1; rc=$?
  sed 's/^/║  /' "$out" | tail -40
  local status="present"; [ $rc -ne 0 ] && status="absent (fine for --sim)"
  printf '╚══ %s\n\n' "$status"; record "$name" "$status" 0 "$out"
}

skip() {
  STEP=$((STEP + 1))
  printf '── %s. %s: skipped (%s)\n\n' "$STEP" "$1" "$2"
  RESULTS="$RESULTS$STEP|$1|skipped: $2|
"
  echo "### $STEP. $1: skipped ($2)" >> "$LOG"; echo >> "$LOG"
}

finish() {
  {
    echo "| # | step | result | time |"
    echo "|---|---|---|---|"
    printf '%s' "$RESULTS" | while IFS='|' read -r n s r t; do [ -n "$n" ] && echo "| $n | $s | $r | $t |"; done
    echo
  } >> "$LOG"
  echo "log: $LOG"
  exit "$1"
}

# ── the steps ────────────────────────────────────────────────────────────────────────────

env_report() {
  sw_vers
  xcodebuild -version
  if xcodebuild -checkFirstLaunchStatus >/dev/null 2>&1; then echo "Xcode components: installed"; else echo "Xcode components: MISSING (sudo xcodebuild -runFirstLaunch)"; return 1; fi
  echo "tt-station: $TTSTATION"
  # The same check the installer and the app use, so "official" means one thing everywhere: a
  # foreign or stale `tt` (exit 3) fails just like a missing one (exit 6). A real run needs it for
  # step 8's right-sizing; --sim skips step 8, so there it's only reported.
  local tt_rc=0
  "$REPO/macos/scripts/ensure-official-tt.sh" --check || tt_rc=$?
  if [ $tt_rc -ne 0 ]; then
    echo "official tt: NOT ready (ensure-official-tt.sh --check exit $tt_rc; run it without --check to install)"
    [ $SIM -eq 0 ] && return 1
  fi
  echo "blackhole-py: $BHPY @ $(git -C "$BHPY" log --oneline -1 2>/dev/null)"
  echo "python: $("$PY" --version 2>&1) ($PY)"
}

card_on_bus() {
  "$TTSTATION" local --no-models && "$TTSTATION" --json local --no-models | grep -q '"board_type": "p100a"\|"chip": "blackhole"'
}

install_and_activate() {
  "$HERE/scripts/install-dev.sh" --team "$TEAM"
  local rc=$?
  [ $rc -eq 0 ] && return 0
  if [ $rc -eq 5 ]; then                              # accepted, but only live after a restart
    echo "The extension activates after a reboot. Restart, then re-run this script with --skip-install."
    return $rc
  fi
  [ $rc -ne 4 ] && return $rc
  echo "Waiting for you to approve the extension (System Settings > General > Login Items & Extensions > Driver Extensions)…"
  local i
  for i in $(seq 1 120); do                           # 10 minutes
    if "$HOSTAPP" status 2>/dev/null | grep -q '\[activated enabled\]'; then "$HOSTAPP" status; return 0; fi
    sleep 5
  done
  echo "not approved within 10 minutes"; return 1
}

driver_attached() {
  local i
  for i in $(seq 1 30); do
    if "$TTSTATION" --json local --no-models | grep -q '"driver": "ttstation-blackhole"'; then
      "$TTSTATION" local --no-models; return 0
    fi
    sleep 1
  done
  "$TTSTATION" local --no-models; echo "the dext did not claim the card within 30 s"; return 1
}

start_broker() {
  if [ $SIM -eq 1 ]; then
    make -s -C "$HERE/bhpy" build/ttbh-broker-sim || return 1
    "$HERE/bhpy/build/ttbh-broker-sim" "$TTBH_BROKER_SOCKET" 2>"$WORK/broker.log" &
  else
    "$HOSTAPP" serve 2>"$WORK/broker.log" &
  fi
  BROKER_PID=$!
  local i sock="${TTBH_BROKER_SOCKET:-$HOME/Library/Application Support/TTStation/ttbh.sock}"
  for i in $(seq 1 100); do [ -S "$sock" ] && break; sleep 0.1; done
  cat "$WORK/broker.log"
  "$PY" -m ttstation_bhpy doctor "$BHPY"
}

compile_kernels() { (cd "$BHPY" && "$PY" -m ttstation_bhpy . examples/matmul_peak.py 512 512 512) 2>&1 | grep -v 'PyTorch was not found'; return "${PIPESTATUS[0]}"; }
matmul_on_card()  { (cd "$BHPY" && "$PY" -m ttstation_bhpy . examples/matmul_peak.py 512 512 512 --run --runs 1 --full-validation) 2>&1 | grep -v 'PyTorch was not found'; return "${PIPESTATUS[0]}"; }
boot_frontier() {
  (cd "$BHPY" && "$PY" - <<'EOF'
import ttstation_bhpy
ttstation_bhpy.toolchain.apply()
ttstation_bhpy.install(".")
import device
dev = device.Device(sysmem_size=64 << 20)
try:
    dev.boot()
    raise SystemExit("boot() returned on a SIMULATED chip, which can't run firmware: something is faking")
except TimeoutError as e:
    print(f"boot() reached the chip-execution frontier as expected: {e}")
finally:
    dev.pcie.close()
EOF
  ) 2>&1 | grep -v 'PyTorch was not found'; return "${PIPESTATUS[0]}"
}

step "Environment" env_report
if [ $SIM -eq 1 ]; then note "Card on the bus" card_on_bus; else step "Card on the bus" card_on_bus; fi
if [ $SIM -eq 1 ]; then
  skip "Install + activate the dext" "--sim"
  skip "Driver attached" "--sim"
  skip "Probe (M1)" "--sim: needs the dext"
  skip "NOC read (M2)" "--sim: needs the dext"
  skip "DMA loopback (M3)" "--sim: needs the dext"
  skip "tt-station local with telemetry (M4)" "--sim: needs the dext"
else
  if [ $SKIP_INSTALL -eq 1 ]; then skip "Install + activate the dext" "--skip-install"; else step "Install + activate the dext" install_and_activate; fi
  step "Driver attached" driver_attached
  step "Probe (M1)" "$HOSTAPP" probe
  step "NOC read (M2)" "$HOSTAPP" probe --noc
  step "DMA loopback (M3)" "$HOSTAPP" probe --dma
  step "tt-station local with telemetry (M4)" "$TTSTATION" local
fi
step "Broker + blackhole-py doctor" start_broker
step "Kernels compile (host only)" compile_kernels
if [ $SIM -eq 1 ]; then
  step "boot() reaches the chip-execution frontier" boot_frontier
else
  step "Matmul on the P100A" matmul_on_card
fi
finish 0
