#!/bin/bash
# build-deb.sh — build Debian packages for tt-station.
#
#   1. Vendors crate deps into vendor/ (offline builds)
#   2. Writes .cargo/config.toml redirecting cargo to vendor/
#   3. Runs dpkg-buildpackage to produce the .deb files
#
# Usage:
#   ./build-deb.sh           # full (re-vendor)
#   ./build-deb.sh --quick   # skip re-vendoring (vendor/ already present)
#
# Output: ../tt-station_*.deb and ../tt-station-panel_*.deb
# Prereqs: sudo apt install devscripts debhelper rustc cargo
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

SKIP_VENDOR=false
for arg in "$@"; do
    case "$arg" in
        --quick) SKIP_VENDOR=true ;;
        --help|-h) sed -n '2,14p' "$0" | sed 's/^# //'; exit 0 ;;
    esac
done

for cmd in cargo dpkg-buildpackage dh; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' not found. Install with:"
        echo "  sudo apt install devscripts debhelper rustc cargo"
        exit 1
    fi
done

echo "╔══════════════════════════════════════════"
echo "║  tt-station Debian package builder"
echo "╚══════════════════════════════════════════"

if [ "$SKIP_VENDOR" = true ] && [ -d vendor ]; then
    echo "⏭  Skipping vendor (--quick, vendor/ already exists)"
else
    echo "📦 Vendoring crate dependencies…"
    rm -rf vendor
    rm -f .cargo/config.toml
    cargo vendor vendor/ 2>&1 | grep -v "^$" || true
fi

mkdir -p .cargo
cat > .cargo/config.toml <<'EOF'
# Generated by build-deb.sh — do not edit. Redirects crate lookups to vendor/.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF
echo "✍  Wrote .cargo/config.toml (vendor redirect)"

# dpkg-checkbuilddeps validates Build-Depends against APT's rustc, which on
# noble is too old for `rustc (>= 1.93)`. Skip that check whenever rustc isn't
# the apt one (rustup/CI); the top-of-script check already confirmed the tools.
SKIP_DEP_FLAG=""
if [ "${GITHUB_ACTIONS:-}" = "true" ] || [ "$(command -v rustc)" != "/usr/bin/rustc" ]; then
    SKIP_DEP_FLAG="-d"
    echo "ℹ  Skipping apt Build-Depends check (toolchain: $(command -v rustc))"
fi

echo "🔨 dpkg-buildpackage…"
dpkg-buildpackage -us -uc -b -jauto $SKIP_DEP_FLAG

echo "✅ Build complete. Packages:"
find .. -maxdepth 1 -name 'tt-station*.deb' -exec ls -lh {} \;
echo "Inspect: dpkg-deb --contents ../tt-station_*.deb"
